# Generated by Django 5.0.6 on 2024-05-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0004_rename_blog_id_commentonblog_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentonblog',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='likeonblog',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
