# Generated by Django 5.0.6 on 2024-05-11 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0005_commentonblog_start_date_likeonblog_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likeonblog',
            old_name='blog_id',
            new_name='blog',
        ),
    ]
